import type { CodegenConfig } from "@graphql-codegen/cli";
import { SAAS_API_ENDPOINT, SAAS_API_KEY } from "./src/constants/env";
import { CLIENT_APP_CONFIG } from "./src/constants/app";

// eslint-disable-next-line no-console
console.log(`[Codegen] URL: ${SAAS_API_ENDPOINT}`);

const { primary, accent } = CLIENT_APP_CONFIG.colours;

const config: CodegenConfig = {
  overwrite: true,
  schema: {
    [SAAS_API_ENDPOINT]: {
      headers: {
        "x-api-key": SAAS_API_KEY,
        Authorization: SAAS_API_KEY,
      },
    },
  },
  generates: {
    "./src/types/gql.ts": {
      plugins: [
        "typescript",
        {
          add: {
            content:
              "/* auto-generated by graphql-codegen */\n/* eslint-disable eslint-comments/no-unlimited-disable */\n/* eslint-disable */",
          },
        },
        {
          add: {
            content: "/* eslint-enable */",
            placement: "append",
          },
        },
      ],
    },
    "./src/styles/globals.css": {
      plugins: [
        {
          add: {
            content:
              "/* auto-generated by graphql-codegen */\n@tailwind base;\n@tailwind components;\n@tailwind utilities;\n",
          },
        },
        {
          add: {
            content: `:root {
  --skylarktv-primary-color: ${primary.startsWith("#") ? primary : `#${primary}`};
  --skylarktv-accent-color: ${accent.startsWith("#") ? accent : `#${accent}`};
}`,
          },
        },
      ],
    },
  },
  hooks: { afterAllFileWrite: ["prettier --write"] },
};

export default config;
