name: Run Content Ingestor
description: Runs the content ingestor on a given Skylark
inputs:
  airtable-base-id:
    description: The Airtable Base to use
    required: false
  airtable-api-key:
    description: The Airtable API key
    required: false
  skylark-api-url:
    description: The Skylark API URL
    required: true
  cognito-aws-region:
    description: The Cognito AWS Region
    required: true
  cognito-client-id:
    description: The Cognito Client ID
    required: true
  cognito-user-pool-id:
    description: The Cognito User Pool ID
    required: true
  cognito-identity-pool-id:
    description: The Cognito Identity Pool ID
    required: true
  amplify-storage-bucket:
    description: Workflow Service bucket for asset upload
    required: true
  cognito-email:
    description: The Cognito Email
    required: true
  cognito-password:
    description: The Cognito Password
    required: true
  create-additional-objects:
    description: Whether to create additional objects (sets and dynamic objects) which SkylarkTV requires to run
    required: true
  saas-ingest:
    description: Whether to target Skylark X or not
    required: false
    default: "false"
  saas-api-token:
    description: Access token to use in API Requests, SLX only
    required: false
  content-type:
    description: The content type to ingest (CONTENT_TYPE) (all, skylarktv or slxdemos)
    deprecationMessage: SLX Demos have been moved to a standalone Airtable base. All content in a base is now ingested
    required: false
    default: "all"
  skylarktv-setup-only:
    description: Only make set up changes (Add object types, enum values, dimensions)
    required: false
    default: "false"
  skylarktv-create-only:
    description: Only create objects (no updates)
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: yarn
    - name: Install deps
      shell: bash
      working-directory: ${{ github.action_path }}/../../../
      run: yarn
    # Uses a retry action in case of a random Skylark error
    - name: Run ingestor
      uses: nick-fields/retry@v2
      env:
        AIRTABLE_API_KEY: ${{ inputs.airtable-api-key }}
        AIRTABLE_BASE_ID: ${{ inputs.airtable-base-id }}
        SKYLARK_API_URL: ${{ inputs.skylark-api-url }}
        COGNITO_EMAIL: ${{ inputs.cognito-email }}
        COGNITO_PASSWORD: ${{ inputs.cognito-password }}
        COGNITO_AWS_REGION: ${{ inputs.cognito-aws-region }}
        COGNITO_CLIENT_ID: ${{ inputs.cognito-client-id }}
        COGNITO_USER_POOL_ID: ${{ inputs.cognito-user-pool-id }}
        COGNITO_IDENTITY_POOL_ID: ${{ inputs.cognito-identity-pool-id }}
        AMPLIFY_STORAGE_BUCKET: ${{ inputs.amplify-storage-bucket }}
        CREATE_SETS: ${{ inputs.create-additional-objects }}
        SAAS_API_ENDPOINT: ${{ inputs.skylark-api-url }}
        SAAS_API_KEY: ${{ inputs.saas-api-token }}
        SKYLARKTV_SETUP_ONLY: ${{ inputs.skylarktv-setup-only }}
        CREATE_ONLY: ${{ inputs.skylarktv-create-only }}
      with:
        timeout_minutes: 30
        retry_wait_seconds: 10
        max_attempts: 5
        retry_on: error
        command: cd ./packages/ingestor && yarn ingest
