name: Deploy to Custom Skylark
on:
  workflow_dispatch:
    inputs:
      launcher-url:
        type: string
        required: true
        description: The Launcher URL for the Skylark instance
      aws-access-key-id:
        type: string
        required: true
        description: AWS account key ID to use
      aws-secret-access-key:
        type: string
        required: true
        description: AWS secret access key to use
concurrency:
  group: deploy-app-${{ inputs.launcher-url }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      domain: ${{ steps.sanitize-url.outputs.result }}
      aws-access-key-id: ${{ steps.mask.outputs.aws-access-key-id }}
      aws-secret-access-key: ${{ steps.mask.outputs.aws-secret-access-key }}
    steps:
      # - name: Mask AWS Credentials
      #   # Workaround for masking workflow_dispatch inputs https://github.com/actions/runner/issues/643
      #   run: |
      #     ACCESS_KEY_ID=$(jq -r '.inputs.aws-access-key-id' $GITHUB_EVENT_PATH)
      #     SECRET_KEY_ID=$(jq -r '.inputs.aws-secret-access-key' $GITHUB_EVENT_PATH)
      #     echo "::add-mask::$ACCESS_KEY_ID"
      #     echo "::add-mask::$SECRET_KEY_ID"
      - uses: actions/github-script@v6
        name: Mask AWS Credentials
        id: mask
        # Workaround for masking workflow_dispatch inputs https://github.com/actions/runner/issues/643
        # env:
        #   ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        #   SECRET_KEY_ID: ${{ inputs.aws-secret-access-key }}
        with:
          script: |
            console.log(context.payload)
            const accessKeyId = context.payload.inputs["aws-access-key-id"];
            const secretAccessKey = context.payload.inputs["aws-secret-access-key"];
            core.setSecret(accessKeyId);
            core.setSecret(secretAccessKey);
            console.log("ACCESS_KEY_ID", accessKeyId);
            console.log("SECRET_KEY_ID", secretAccessKey);
            core.setOutput("aws-access-key-id", accessKeyId);
            core.setOutput("aws-secret-access-key", secretAccessKey);
            process.exit(1)

      - uses: ./.github/actions/parse-domain-from-url
        id: sanitize-url
        with:
          url: ${{ inputs.launcher-url }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          base-domain: ${{ needs.prepare.outputs.domain }}
          # TODO don't assume the API URL will be "api."
          skylark-api-url: https://api.${{ needs.prepare.outputs.domain }}
          aws-access-key-id: ${{ needs.prepare.outputs.aws-access-key-id }}
          aws-secret-access-key: ${{ needs.prepare.outputs.aws-secret-access-key }}
