name: Deploy App
on: push
concurrency:
  group: deploy-app
env:
  pr-comment-id: reference-apps-deployment
  pr-comment-title: "Reference Apps Deployment"
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      git-branch: ${{ steps.branch-and-ref.outputs.branch }}
      git-ref: ${{ steps.branch-and-ref.outputs.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Comment building status on PR
        uses: ostmodern/comment-url-on-pr@v1
        with:
          title: ${{ env.pr-comment-title }}
          comment_id: ${{ env.pr-comment-id }}
          status: building
          github_token: ${{ github.token }}
      - name: Get branch and ref
        id: branch-and-ref
        run: |
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.event.ref = ${{ github.event.ref }}"

          # If the event is delete, use the event ref
          if [ "${{ github.event_name }}" = delete ]; then
            GitRef="${{ github.event.ref }}"
          elif [ "${{ github.event_name }}" = pull_request ]; then
            GitRef="${{ github.head_ref }}"
          else
            GitRef="${{ github.ref }}"
          fi
          GitBranch=$(echo ${GitRef#refs/heads/})

          echo "Git Ref: $GitRef"
          echo "Git Branch Name: $GitBranch"

          echo "::set-output name=ref::$GitRef"
          echo "::set-output name=branch::$GitBranch"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: prepare
    outputs:
      url: ${{ steps.cdk.outputs.url }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Use skylark-dev account on main branch
          aws-access-key-id: ${{ needs.prepare.outputs.git-branch == 'main' && secrets.AWS_ACCESS_KEY_ID_SKYLARK_DEV || secrets.AWS_ACCESS_KEY_ID_LEGACY_SKYLARK_DEVELOPMENT }}
          aws-secret-access-key: ${{ needs.prepare.outputs.git-branch == 'main' && secrets.AWS_SECRET_ACCESS_KEY_SKYLARK_DEV || secrets.AWS_SECRET_ACCESS_KEY_LEGACY_SKYLARK_DEVELOPMENT }}
          aws-region: us-east-1
      - uses: ./.github/actions/deploy
        id: cdk
        with:
          git-branch: ${{ needs.prepare.outputs.git-branch }}
          # hardcode domains until more accounts are supported
          base-domain: ${{ needs.prepare.outputs.git-branch == 'main' && 'skylark-dev.skylarkplatform.io' || 'legacy-skylark-development.skylarkplatform.io' }}
          sentry-token: ${{ secrets.SENTRY_TOKEN }}

  signal:
    name: Signal
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - uses: actions/github-script@v6
        id: additional-urls
        with:
          result-encoding: string
          script: |
            const json = JSON.stringify([
              { label: "Media", value: "${{ needs.deploy.outputs.url }}" },
            ]);
            return json;
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Comment status on PR
        uses: ostmodern/comment-url-on-pr@v1
        with:
          title: ${{ env.pr-comment-title }}
          comment_id: ${{ env.pr-comment-id }}
          status: ${{ env.WORKFLOW_CONCLUSION }}
          github_token: ${{ github.token }}
          additional_urls: ${{ steps.additional-urls.outputs.result }}
