name: Deploy to Custom Skylark
on:
  workflow_dispatch:
    inputs:
      launcher-url:
        type: string
        required: true
        description: The Launcher URL for the Skylark instance
      aws-access-key-id:
        type: string
        required: true
        description: AWS account key ID to use
      aws-secret-access-key:
        type: string
        required: true
        description: AWS secret access key to use
concurrency:
  group: deploy-app-${{ inputs.launcher-url }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      domain: ${{ steps.sanitize-url.outputs.result }}
    steps:
      # - name: Mask AWS Credentials
      #   # Workaround for masking workflow_dispatch inputs https://github.com/actions/runner/issues/643
      #   run: |
      #     ACCESS_KEY_ID=$(jq -r '.inputs.aws-access-key-id' $GITHUB_EVENT_PATH)
      #     SECRET_KEY_ID=$(jq -r '.inputs.aws-secret-access-key' $GITHUB_EVENT_PATH)
      #     echo "::add-mask::$ACCESS_KEY_ID"
      #     echo "::add-mask::$SECRET_KEY_ID"
      - uses: actions/github-script@v6
        name: Mask AWS Credentials
        # Workaround for masking workflow_dispatch inputs https://github.com/actions/runner/issues/643
        env:
          ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
          SECRET_KEY_ID: ${{ inputs.aws-secret-access-key }}
        with:
          result-encoding: string
          script: |
            core.setSecret(process.env.ACCESS_KEY_ID);
            core.setSecret(process.env.SECRET_KEY_ID);
            console.log("ACCESS_KEY_ID", process.env.ACCESS_KEY_ID);
            console.log("SECRET_KEY_ID", process.env.SECRET_KEY_ID);

      - uses: ./.github/actions/parse-domain-from-url
        id: sanitize-url
        with:
          url: ${{ inputs.launcher-url }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          base-domain: ${{ needs.prepare.outputs.domain }}
          # TODO don't assume the API URL will be "api."
          skylark-api-url: https://api.${{ needs.prepare.outputs.domain }}
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
