name: Add SkylarkTV Content to a Skylark Account
on:
  workflow_dispatch:
    inputs:
      skylark_url:
        type: string
        default: https://api.sl-develop.development.skylarkplatform.com/graphql
        required: true
        description: Your Skylark's GraphQL URL, should end with /graphql. Default to sl-develop-10's URL.
      skylark_api_key:
        type: string
        required: true
        description: Your Skylark API Key.
      skylarktv_setup_only:
        type: boolean
        required: false
        default: false
        description: Only setup SkylarkTV - Add object types, enum values, dimensions etc
      skylarktv_create_only:
        type: boolean
        required: false
        default: false
        description: Only create objects (no updates)
concurrency:
  group: ingest-skylarktv-content-${{ github.event.inputs.skylark_url }}
  cancel-in-progress: true
jobs:
  ingestor:
    name: Ingest SkylarkTV Content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mask API key input
        id: add_mask
        run: |
          API_KEY=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.skylark_api_key' )
          echo ::add-mask::$API_KEY
          echo SKYLARK_API_KEY="$API_KEY" >> $GITHUB_ENV
      - uses: ./.github/actions/run-ingestor
        with:
          airtable-api-key: ${{ secrets.AIRTABLE_API_KEY }}
          airtable-base-id: ${{ secrets.AIRTABLE_BASE_ID }}
          skylark-api-url: ${{ github.event.inputs.skylark_url }}
          create-additional-objects: "true"
          saas-ingest: "true"
          saas-api-token: ${{ env.SKYLARK_API_KEY }}
          content-type: "skylarktv"
          skylarktv-setup-only: ${{ github.event.inputs.skylarktv_setup_only }}
          skylarktv-create-only: ${{ github.event.inputs.skylarktv_create_only }}
