name: Lighthouse
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          type: "all"
          urls: "https://media.feature-add-axios.apps.skylark-dev.skylarkplatform.io/"
          gitHubAccessToken: ${{ github.token }}
          slackWebhookUrl: ${{ secrets.SLACK_ALERTS_FE_TESTING }}
