name: Lighthouse
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: "https://media.feature-add-axios.apps.skylark-dev.skylarkplatform.io/"
          slackWebhookUrl: ${{ secrets.SLACK_ALERTS_CYPRESS_PERCY_CHROMATIC_WEBHOOK_URL }}
