name: Lighthouse
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: "https://media.feature-add-axios.apps.skylark-dev.skylarkplatform.io/"
          gitHubAccessToken: ${{ github.token }}
          slackWebhookUrl: ${{ secrets.SLACK_ALERTS_CYPRESS_PERCY_CHROMATIC_WEBHOOK_URL }}
      - name: Verify Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "40"
          minBestPracticesScore: "40"
          minPerformanceScore: "40"
          minProgressiveWebAppScore: "40"
          minSeoScore: "40"
