name: Pull Request Checks
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint, Prettier & Jest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn prettier:check
      - run: yarn test:ci
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Frontend Unit Test Results
          path: "!(node_modules)/**/reports/jest-junit.xml"
          reporter: jest-junit

  build:
    needs: lint
    runs-on: ubuntu-latest
    name: Build All Apps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn
      # Check all apps build
      - run: yarn lerna-run build --parallel
