name: Pull Request Checks
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: pr-checks-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint, Prettier & Jest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn prettier:check
      - run: yarn test:ci
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Frontend Unit Test Results
          path: "!(node_modules)/**/reports/jest-junit.xml"
          reporter: jest-junit
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: "https://media.feature-add-axios.apps.skylark-dev.skylarkplatform.io/"

  build-and-test:
    needs: lint
    runs-on: ubuntu-latest
    name: Build and test ${{ matrix.tests.app }} app
    strategy:
      matrix:
        tests: [{ app: "media", percy_secret: "PERCY_MEDIA_APP_TOKEN" }]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn
      - run: yarn build
        env:
          NEXT_PUBLIC_SKYLARK_API_URL: https://api.showcase-test.eng-james-wallis.skylarkplatform.io
        working-directory: apps/${{ matrix.tests.app }}
      - run: yarn test:percy
        working-directory: apps/${{ matrix.tests.app }}
        env:
          PERCY_TOKEN: ${{ secrets[matrix.tests.percy_secret] }}

  chromatic:
    needs: lint
    runs-on: ubuntu-latest
    name: Deploy Chromatic
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/storybook
          autoAcceptChanges: main
